services:
  mediawiki:
    build: .
    restart: always
    ports:
      - 8081:80
    links:
      - database
    volumes:
      - /var/www/html/images
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
      - ./staging_area:/var/www/html/staging_area
      - ./imports_externes:/var/www/html/imports_externes
    environment:
      - MW_ADMIN_USER=admin
      - MW_ADMIN_PASS=admin123
      - MW_DB_SERVER=database
      - MW_DB_NAME=my_wiki
      - MW_DB_USER=wikiuser
      - MW_DB_PASS=wikipass
      - MW_SITE_NAME=DocDFAED

  database:
    image: mariadb:10.4
    restart: always
    environment:
      - MYSQL_DATABASE=my_wiki
      - MYSQL_USER=wikiuser
      - MYSQL_PASSWORD=wikipass
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - db_data_docdfa:/var/lib/mysql

volumes:
  db_data_docdfa:
